version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # Alibaba Cloud
    container_name: pg
    restart: always
    ports: # It's recommended not to expose ports in production
      - 5432:5432
    networks:
      - fastgpt
    environment:
      # These configurations only take effect on the first run. To apply changes, delete persistent data and restart.
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
    container_name: mongo
    restart: always
    ports: # It's recommended not to expose ports in production
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # These configurations only take effect on the first run. To apply changes, delete persistent data and restart.
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    # image: c121914yu/fast-gpt:latest # Docker Hub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # Root password, username: root
      - DEFAULT_ROOT_PSW=1234
      # Transfer address, not necessary if using official account
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # Database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      # MongoDB configuration, no need to change
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      # PostgreSQL configuration.
      - PG_HOST=pg
      - PG_PORT=5432
      - PG_USER=username
      - PG_PASSWORD=password
      - PG_DB_NAME=postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fastgpt:
# host version, not recommended
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # Docker Hub
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # Alibaba Cloud
    container_name: pg
    restart: always
    ports: # It's recommended not to expose ports in production
      - 5432:5432
    environment:
      # These configurations only take effect on the first run. To apply changes, delete persistent data and restart.
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # Alibaba Cloud
    container_name: mongo
    restart: always
    ports: # It's recommended not to expose ports in production
      - 27017:27017
    environment:
      # These configurations only take effect on the first run. To apply changes, delete persistent data and restart.
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/logs:/var/log/mongodb
  fastgpt:
    # image: ghcr.io/c121914yu/fastgpt:latest # GitHub
    # image: c121914yu/fast-gpt:latest # Docker Hub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # Alibaba Cloud
    network_mode: host
    restart: always
    container_name: fastgpt
    environment:
      # Root password, username: root
      - DEFAULT_ROOT_PSW=1234
      # Transfer address, not necessary if using official account
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # Database max link
      # Token encryption credential (fill with anything as a login credential)
      - TOKEN_KEY=any
      # Root key, highest privilege, can call internal interfaces
      - ROOT_KEY=root_key
      # MongoDB configuration, no need to change
      - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      # PostgreSQL configuration
      - PG_HOST=0.0.0.0
      - PG_PORT=5432
      - PG_USER=username
      - PG_PASSWORD=password
      - PG_DB_NAME=postgres
