name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set output
        id: vars
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
      - name: Release Helm
        run: |
          echo ${{ secrets.GH_PUBLISH_SECRETS }} | helm registry login ghcr.io -u ${{ secrets.GH_USER }} --password-stdin
          export APP_VERSION=${{ steps.vars.outputs.tag }}
          export HELM_VERSION=${{ steps.vars.outputs.tag }}
          if [[ ! "$line" =~ ^v ]]
          then
            unset APP_VERSION
            unset HELM_VERSION
          fi
          helm package files/helm/fastgpt --version ${HELM_VERSION}-helm --app-version ${APP_VERSION} -d bin
          helm push bin/fastgpt-${HELM_VERSION}-helm.tgz oci://${HELM_REPO}
