name: deploy fastgpt to docker  and  ssh

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # 检查代码
      - name: Checkout
        uses: actions/checkout@v2
        
      # 发布
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
      - name: Build and Push Docker Image
        env:
          app_name: 'yangyayuan'
          app_space: 'fastgpt666'
          app_url: 'registry.cn-hangzhou.aliyuncs.com'
        run: |
          docker build -t $app_url/$app_space/$app_name:latest .
          docker push $app_url/$app_space/$app_name:latest

      # 部署
      - name: Login aliEcs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_TOKEN }}
          port: 22
          env:
            app_name: 'yangyayuan'
            app_space: 'fastgpt666'
            app_url: 'registry.cn-hangzhou.aliyuncs.com'
          run: |
            if test -n "$(docker ps -a |grep $app_name)"; then
              echo "停止并删除容器和上版本镜像"
              docker stop $app_name
              docker rm $app_name
              docker rmi $app_url/$app_space/$app_name:latest
            else
              echo "未检查到$app_name容器运行"
            fi
            echo "拉取最新的镜像并启动服务"
            docker run --name $app_name -p 80:80 -d $app_url/$app_space/$app_name:latest
