name: Release

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt update && sudo  apt install  -y nodejs npm
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to  gitbub
        uses: docker/login-action@v2
        with:
          #registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish image
        env:
          # fork friendly ^^
<<<<<<< HEAD
          # DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/fast-gpt
          DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/fast-gpt
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --label "org.opencontainers.image.source=https://github.com/${{ secrets.repository_owner }}/FastGPT" \
          --label "Maintainer: <muaimingjun && Paper-Dragon>" \
          --label "org.opencontainers.image.description=fast-gpt image" \
=======
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/fastgpt
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/FastGPT" \
          --label "org.opencontainers.image.description=fastgpt image" \
>>>>>>> 5f66f4523cacd07789b1a5eef23c8aca1c9bc1ca
          --label "org.opencontainers.image.licenses=MIT" \
          --push \
          -t ${DOCKER_REPO}:latest \
          -f Dockerfile \
          .
